In [ ]:
pip install botorch

In [2]:
import pandas as pd
import torch

#import random
#random.seed(0)
#import numpy as np
#np.random.seed(0)

train_data = pd.read_excel('data_sample_multiple_components_GLU_9objs.xlsx')
#print(train_data)
train_x = train_data.iloc[:,[0,1]].values
#print(train_X)
train_x = torch.tensor(train_x, dtype=torch.float32)
print(train_x)

train_obj = train_data.iloc[:,2:].values
#print(train_Y)
train_obj = torch.tensor(train_obj, dtype=torch.float32)
print(train_obj)

tensor([[0.0050, 0.5000],
        [0.0050, 0.5000],
        [0.0050, 0.5000],
        [0.0050, 0.5000],
        [0.0050, 1.0000],
        [0.0050, 1.0000],
        [0.0050, 1.0000],
        [0.0050, 1.0000],
        [0.0050, 2.0000],
        [0.0050, 2.0000],
        [0.0050, 2.0000],
        [0.0050, 2.0000],
        [0.0406, 0.5000],
        [0.0406, 0.5000],
        [0.0406, 0.5000],
        [0.0406, 0.5000],
        [0.0406, 1.0000],
        [0.0406, 1.0000],
        [0.0406, 1.0000],
        [0.0406, 1.0000],
        [0.0406, 2.0000],
        [0.0406, 2.0000],
        [0.0406, 2.0000],
        [0.0406, 2.0000]])
tensor([[ 0.0450,  0.0500,  0.0090,  0.0190,  0.1520,  0.0000,  0.0210,  0.0270,
         -0.1990],
        [ 0.0390,  0.0540,  0.0130,  0.0640,  0.1800,  0.0000,  0.0260,  0.0210,
         -0.1990],
        [ 0.0470,  0.0660,  0.0140,  0.0280,  0.2280,  0.0000,  0.0330,  0.0400,
         -0.1990],
        [ 0.0430,  0.0570,  0.0120,  0.0370,  0.1870,  0.0000,  0.0270,  0.

In [3]:
from botorch import fit_gpytorch_model
from botorch.models.gp_regression import FixedNoiseGP
from botorch.models.transforms.outcome import Standardize
from botorch.models.model_list_gp_regression import ModelListGP
from gpytorch.mlls.sum_marginal_log_likelihood import SumMarginalLogLikelihood
from botorch.utils.transforms import unnormalize, normalize
from botorch.utils.multi_objective.box_decompositions.non_dominated import FastNondominatedPartitioning
from botorch.acquisition.multi_objective.monte_carlo import qExpectedHypervolumeImprovement, qNoisyExpectedHypervolumeImprovement
from botorch.acquisition.monte_carlo import qNoisyExpectedImprovement
from botorch.sampling.samplers import SobolQMCNormalSampler
from botorch.optim.optimize import optimize_acqf, optimize_acqf_list
from botorch.acquisition.objective import GenericMCObjective
from botorch.utils.multi_objective.scalarization import get_chebyshev_scalarization
from botorch.utils.sampling import sample_simplex

torch.manual_seed(0)

NOISE_SE = torch.tensor([1,1,1,1,1,1,1,1,1])
#print(NOISE_SE)

# define models for objective and constraint
models = []
for i in range(train_obj.shape[-1]):
    train_y = train_obj[..., i:i+1]
    train_yvar = torch.full_like(train_y, NOISE_SE[i] ** 2)
    models.append(FixedNoiseGP(train_x, train_y, train_yvar, outcome_transform=Standardize(m=1)))
model = ModelListGP(*models)
mll = SumMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll)

BATCH_SIZE = 10
NUM_RESTARTS = 2
RAW_SAMPLES = 4
MC_SAMPLES = 16

standard_bounds = torch.tensor([[0.001, 0.1],[0.05, 3]])
#print(standard_bounds)
ref_point=torch.tensor([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0])
sampler = SobolQMCNormalSampler(num_samples=MC_SAMPLES)

#train_x = normalize(train_x, problem.bounds)
with torch.no_grad():
    pred = model.posterior(train_x).mean
acq_func_list = []
for _ in range(BATCH_SIZE):
    #weights = sample_simplex(problem.num_objectives, **tkwargs).squeeze()
    weights = sample_simplex(9).squeeze()
    objective = GenericMCObjective(get_chebyshev_scalarization(weights=weights, Y=pred))
    acq_func = qNoisyExpectedImprovement(  # pyre-ignore: [28]
        model=model,
        objective=objective,
        X_baseline=train_x,
        sampler=sampler,
        prune_baseline=True,
    )
    acq_func_list.append(acq_func)
# optimize
candidates, _ = optimize_acqf_list(
    acq_function_list=acq_func_list,
    bounds=standard_bounds,
    num_restarts=NUM_RESTARTS,
    raw_samples=RAW_SAMPLES,  # used for intialization heuristic
    options={"batch_limit": 5, "maxiter": 200},
)
# observe new values 
#new_x =  unnormalize(candidates.detach(), bounds=problem.bounds)
print(candidates)

/usr/local/lib/python3.7/dist-packages/gpytorch/lazy/lazy_tensor.py:1741: UserWarning: torch.triangular_solve is deprecated in favor of torch.linalg.solve_triangularand will be removed in a future PyTorch release.
torch.linalg.solve_triangular has its arguments reversed and does not return a copy of one of the inputs.
X = torch.triangular_solve(B, A).solution
should be replaced with
X = torch.linalg.solve_triangular(A, B). (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1672.)
  Linv = torch.triangular_solve(Eye, L, upper=False).solution
/usr/local/lib/python3.7/dist-packages/gpytorch/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  NumericalWarning,
/usr/local/lib/python3.7/dist-packages/gpytorch/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  NumericalWarning,
/usr/local/lib/python3.7/dist-packages/gpytorch/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitte

tensor([[1.0000e-03, 1.4010e+00],
        [1.0000e-03, 1.5228e-01],
        [1.0000e-03, 3.0000e+00],
        [5.0000e-02, 2.7982e+00],
        [1.0000e-03, 2.5468e+00],
        [1.0000e-03, 2.8806e+00],
        [1.0000e-03, 1.4547e+00],
        [5.0000e-02, 4.7671e-01],
        [5.0000e-02, 2.6761e+00],
        [1.4007e-02, 1.8477e+00]])


In [4]:
for i in range(9):
    print(model.models[i].covar_module.outputscale, 
          model.models[i].covar_module.base_kernel.lengthscale, 
          model.models[i].likelihood.noise)

tensor(6.6369, grad_fn=<SoftplusBackward0>) tensor([[0.3329, 0.3337]], grad_fn=<SoftplusBackward0>) tensor([23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922,
        23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922,
        23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922,
        23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922, 23962.4922])
tensor(6.6329, grad_fn=<SoftplusBackward0>) tensor([[0.3339, 0.3332]], grad_fn=<SoftplusBackward0>) tensor([11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389,
        11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389,
        11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389,
        11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389, 11423.8389])
tensor(6.6523, grad_fn=<SoftplusBackward0>) tensor([[0.3333, 0.3333]], grad_fn=<SoftplusBackward0>) tensor([82449.5938, 82449.5938, 82449.5938, 82449.5938, 82